module EdgeCloudSim {exports edu.boun.edgecloudsim.applications.sample_app5;
exports edu.boun.edgecloudsim.task_generator;
exports edu.boun.edgecloudsim.applications.sample_app4;
exports edu.boun.edgecloudsim.mobility;
exports edu.boun.edgecloudsim.network;
exports edu.boun.edgecloudsim.applications.sample_app1;
exports edu.boun.edgecloudsim.applications.sample_app3;
exports edu.boun.edgecloudsim.applications.sample_app2;
exports edu.boun.edgecloudsim.edge_orchestrator;
exports edu.boun.edgecloudsim.cloud_server;
exports edu.boun.edgecloudsim.edge_server;
exports edu.boun.edgecloudsim.utils;
exports edu.boun.edgecloudsim.core;
exports edu.boun.edgecloudsim.edge_client;
exports edu.boun.edgecloudsim.edge_client.mobile_processing_unit;
requires cloudsim;
requires colt;
requires commons.math3;
requires jFuzzyLogic.v3;
requires java.xml;requires weka;}